[env:seeed_xiao_esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = seeed_xiao_esp32c6
framework = arduino
lib_deps =
    adafruit/Adafruit PCD8544 Nokia 5110 LCD library
    adafruit/Adafruit GFX Library
    greiman/SdFat@^2.2.0
build_src_filter = +<main.cpp>
